services:
  mongo:
    image: mongo
    container_name: container-name
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    command: ["--auth", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro