version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
